### ISSUE TITLE
typo(?) or a compatibility patch for higher pytorch version

### ISSUE THREAD

**Issue by RyougiKukoc** [shizenglin/training-free-object-counter#4]
[automatic_mask_generator.py#L341](https://github.com/shizenglin/training-free-object-counter/blob/main/shi_segment_anything/automatic_mask_generator.py#L341)
```transformed_labels = sim_map[[transformed_points[:,1],transformed_points[:,0]]]```
should be
```transformed_labels = sim_map[transformed_points[:,1],transformed_points[:,0]]```

so should [automatic_mask_generator.py#L341](https://github.com/shizenglin/training-free-object-counter/blob/main/shi_segment_anything/automatic_mask_generator.py#L341) and [automatic_mask_generator_text.py#L340](https://github.com/shizenglin/training-free-object-counter/blob/main/shi_segment_anything/automatic_mask_generator_text.py#L340)

**Comment by shizenglin** [comment]
This typo has been corrected. Thanks!
